CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS public.usuario (
                                              usuario_id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_nome      text NOT NULL,
    usuario_cnpj      varchar(30),
    usuario_nome_social text,
    usuario_cep       varchar(10),
    usuario_endereco  text,
    usuario_numendereco text,
    usuario_bairro    text,
    usuario_fone      varchar(32),
    usuario_cidade    text,
    usuario_estado    varchar(255),
    login             text NOT NULL UNIQUE,
    senha             text NOT NULL
    );

CREATE TABLE IF NOT EXISTS public.categoria (
                                                categoria_id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                categoria_nome text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.unidmedida (
                                                 unidmed_id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 unidmed_nome text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tipopagamento (
                                                    tipopag_id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    tipopag_nome text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.fornecedor (
                                                 fornecedor_id       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    fornecedor_nome     text NOT NULL,
    fornecedor_rsocial  text,
    fornecedor_ie       text,
    fornecedor_cnpj     varchar(30),
    fornecedor_cep      varchar(14),
    fornecedor_endereco text,
    fornecedor_bairro   text,
    fornecedor_fone     varchar(32),
    fornecedor_cel      varchar(32),
    fornecedor_endnumero text,
    fornecedor_cidade   text,
    fornecedor_estado   bpchar(2),
    usuario_id          uuid NOT NULL
    );

CREATE TABLE IF NOT EXISTS public.produto (
                                              produto_id         int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              produto_nome       text NOT NULL,
                                              produto_descricao  text,
                                              produto_valorpago  numeric(12,2),
    produto_valorvenda numeric(12,2),
    unidmed_id         int8,
    categoria_id       int8,
    usuario_id         uuid NOT NULL,
    produto_qtde       int4
    );

CREATE TABLE IF NOT EXISTS public.compra (
                                             compra_id        int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             compra_data      date NOT NULL,
                                             compra_nrfiscal  text,
                                             compra_total     numeric(14,2),
    compra_nparcelas int4,
    compra_status    text,
    fornecedor_id    uuid,
    tipopag_id       int8,
    usuario_id       uuid NOT NULL
    );

CREATE TABLE IF NOT EXISTS public.venda (
                                            venda_id    int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            venda_data  timestamp(6) NOT NULL,
    venda_total numeric(14,2),
    tipopag_id  int8,
    usuario_id  uuid NOT NULL
    );

CREATE TABLE IF NOT EXISTS public.itenscompra (
                                                  itc_id     int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  compra_id  int8 NOT NULL,
                                                  produto_id int8 NOT NULL,
                                                  itc_qtde   int4,
                                                  itc_valor  numeric(12,2)
    );

CREATE TABLE IF NOT EXISTS public.itensvenda (
                                                 itv_id     int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 venda_id   int8 NOT NULL,
                                                 produto_id int8 NOT NULL,
                                                 itv_qtde   int4,
                                                 itv_valor  numeric(12,2),
    itv_custo  numeric(12,2)
    );

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'fornecedor_usuario_id_fkey'
      AND table_schema='public' AND table_name='fornecedor'
  ) THEN
ALTER TABLE public.fornecedor
    ADD CONSTRAINT fornecedor_usuario_id_fkey
        FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id) ON DELETE RESTRICT;
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'produto_categoria_id_fkey'
      AND table_schema='public' AND table_name='produto'
  ) THEN
ALTER TABLE public.produto
    ADD CONSTRAINT produto_categoria_id_fkey
        FOREIGN KEY (categoria_id) REFERENCES public.categoria(categoria_id);
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'produto_unidmed_id_fkey'
      AND table_schema='public' AND table_name='produto'
  ) THEN
ALTER TABLE public.produto
    ADD CONSTRAINT produto_unidmed_id_fkey
        FOREIGN KEY (unidmed_id) REFERENCES public.unidmedida(unidmed_id);
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'produto_usuario_id_fkey'
      AND table_schema='public' AND table_name='produto'
  ) THEN
ALTER TABLE public.produto
    ADD CONSTRAINT produto_usuario_id_fkey
        FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id) ON DELETE RESTRICT;
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'compra_fornecedor_id_fkey'
      AND table_schema='public' AND table_name='compra'
  ) THEN
ALTER TABLE public.compra
    ADD CONSTRAINT compra_fornecedor_id_fkey
        FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedor(fornecedor_id);
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'compra_tipopag_id_fkey'
      AND table_schema='public' AND table_name='compra'
  ) THEN
ALTER TABLE public.compra
    ADD CONSTRAINT compra_tipopag_id_fkey
        FOREIGN KEY (tipopag_id) REFERENCES public.tipopagamento(tipopag_id);
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'compra_usuario_id_fkey'
      AND table_schema='public' AND table_name='compra'
  ) THEN
ALTER TABLE public.compra
    ADD CONSTRAINT compra_usuario_id_fkey
        FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id) ON DELETE RESTRICT;
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'venda_tipopag_id_fkey'
      AND table_schema='public' AND table_name='venda'
  ) THEN
ALTER TABLE public.venda
    ADD CONSTRAINT venda_tipopag_id_fkey
        FOREIGN KEY (tipopag_id) REFERENCES public.tipopagamento(tipopag_id);
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'venda_usuario_id_fkey'
      AND table_schema='public' AND table_name='venda'
  ) THEN
ALTER TABLE public.venda
    ADD CONSTRAINT venda_usuario_id_fkey
        FOREIGN KEY (usuario_id) REFERENCES public.usuario(usuario_id) ON DELETE RESTRICT;
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'itenscompra_compra_id_fkey'
      AND table_schema='public' AND table_name='itenscompra'
  ) THEN
ALTER TABLE public.itenscompra
    ADD CONSTRAINT itenscompra_compra_id_fkey
        FOREIGN KEY (compra_id) REFERENCES public.compra(compra_id) ON DELETE CASCADE;
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'itenscompra_produto_id_fkey'
      AND table_schema='public' AND table_name='itenscompra'
  ) THEN
ALTER TABLE public.itenscompra
    ADD CONSTRAINT itenscompra_produto_id_fkey
        FOREIGN KEY (produto_id) REFERENCES public.produto(produto_id);
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'itensvenda_venda_id_fkey'
      AND table_schema='public' AND table_name='itensvenda'
  ) THEN
ALTER TABLE public.itensvenda
    ADD CONSTRAINT itensvenda_venda_id_fkey
        FOREIGN KEY (venda_id) REFERENCES public.venda(venda_id) ON DELETE CASCADE;
END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'itensvenda_produto_id_fkey'
      AND table_schema='public' AND table_name='itensvenda'
  ) THEN
ALTER TABLE public.itensvenda
    ADD CONSTRAINT itensvenda_produto_id_fkey
        FOREIGN KEY (produto_id) REFERENCES public.produto(produto_id);
END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_produto_usuario    ON public.produto (usuario_id);
CREATE INDEX IF NOT EXISTS idx_produto_categoria  ON public.produto (categoria_id);
CREATE INDEX IF NOT EXISTS idx_produto_unidmed    ON public.produto (unidmed_id);
CREATE INDEX IF NOT EXISTS idx_fornecedor_usuario ON public.fornecedor (usuario_id);
CREATE INDEX IF NOT EXISTS idx_compra_usuario     ON public.compra (usuario_id);
CREATE INDEX IF NOT EXISTS idx_compra_fornecedor  ON public.compra (fornecedor_id);
CREATE INDEX IF NOT EXISTS idx_compra_tipopag     ON public.compra (tipopag_id);
CREATE INDEX IF NOT EXISTS idx_venda_usuario      ON public.venda (usuario_id);
CREATE INDEX IF NOT EXISTS idx_venda_tipopag      ON public.venda (tipopag_id);
CREATE INDEX IF NOT EXISTS idx_itenscompra_compra ON public.itenscompra (compra_id);
CREATE INDEX IF NOT EXISTS idx_itenscompra_prod   ON public.itenscompra (produto_id);
CREATE INDEX IF NOT EXISTS idx_itensvenda_venda   ON public.itensvenda (venda_id);
CREATE INDEX IF NOT EXISTS idx_itensvenda_prod    ON public.itensvenda (produto_id);

ALTER TABLE public.produto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produto FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produto_by_usuario ON public.produto;
CREATE POLICY produto_by_usuario ON public.produto
  USING (usuario_id = current_setting('app.current_usuario', true)::uuid)
  WITH CHECK (usuario_id = current_setting('app.current_usuario', true)::uuid);

ALTER TABLE public.fornecedor ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fornecedor FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS fornecedor_by_usuario ON public.fornecedor;
CREATE POLICY fornecedor_by_usuario ON public.fornecedor
  USING (usuario_id = current_setting('app.current_usuario', true)::uuid)
  WITH CHECK (usuario_id = current_setting('app.current_usuario', true)::uuid);

ALTER TABLE public.compra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compra FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS compra_by_usuario ON public.compra;
CREATE POLICY compra_by_usuario ON public.compra
  USING (usuario_id = current_setting('app.current_usuario', true)::uuid)
  WITH CHECK (usuario_id = current_setting('app.current_usuario', true)::uuid);

ALTER TABLE public.venda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venda FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS venda_by_usuario ON public.venda;
CREATE POLICY venda_by_usuario ON public.venda
  USING (usuario_id = current_setting('app.current_usuario', true)::uuid)
  WITH CHECK (usuario_id = current_setting('app.current_usuario', true)::uuid);

ALTER TABLE public.itenscompra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.itenscompra FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS itenscompra_by_usuario ON public.itenscompra;
CREATE POLICY itenscompra_by_usuario ON public.itenscompra
USING (
  EXISTS (
    SELECT 1 FROM public.compra c
    WHERE c.compra_id = itenscompra.compra_id
      AND c.usuario_id = current_setting('app.current_usuario', true)::uuid
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.compra c
    WHERE c.compra_id = itenscompra.compra_id
      AND c.usuario_id = current_setting('app.current_usuario', true)::uuid
  )
);

ALTER TABLE public.itensvenda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.itensvenda FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS itensvenda_by_usuario ON public.itensvenda;
CREATE POLICY itensvenda_by_usuario ON public.itensvenda
USING (
  EXISTS (
    SELECT 1 FROM public.venda v
    WHERE v.venda_id = itensvenda.venda_id
      AND v.usuario_id = current_setting('app.current_usuario', true)::uuid
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.venda v
    WHERE v.venda_id = itensvenda.venda_id
      AND v.usuario_id = current_setting('app.current_usuario', true)::uuid
  )
);
