
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================
-- Tabela "usuario" (tenant)
-- =========================
CREATE TABLE usuario (
  usuario_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_nome       TEXT NOT NULL,
  usuario_cnpj       VARCHAR(30),
  usuario_nome_social TEXT,
  usuario_cep        VARCHAR(10),
  usuario_endereco   TEXT,
  usuario_numendereco TEXT,
  usuario_bairro     TEXT,
  usuario_fone       VARCHAR(32),
  usuario_cidade     TEXT,
  usuario_estado     CHAR(2),
  login              TEXT NOT NULL UNIQUE,
  senha              TEXT NOT NULL
);

-- =========================
-- Tabela "fornecedor"
-- =========================
CREATE TABLE fornecedor (
  fornecedor_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  fornecedor_nome   TEXT NOT NULL,
  fornecedor_rsocial TEXT,
  fornecedor_ie     TEXT,
  fornecedor_cnpj   VARCHAR(30),
  fornecedor_cep    VARCHAR(14),
  fornecedor_endereco TEXT,
  fornecedor_bairro TEXT,
  fornecedor_fone   VARCHAR(32),
  fornecedor_cel    VARCHAR(32),
  fornecedor_endnumero TEXT,
  fornecedor_cidade TEXT,
  fornecedor_estado CHAR(2),

  -- tenant
  usuario_id        UUID NOT NULL REFERENCES usuario(usuario_id) ON DELETE RESTRICT
);

-- =========================
-- Tabela "categoria"
-- =========================
CREATE TABLE categoria (
  categoria_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_nome  TEXT NOT NULL,

  usuario_id      UUID NOT NULL REFERENCES usuario(usuario_id) ON DELETE RESTRICT
);

-- =========================
-- Tabela "unidmedida"
-- =========================
CREATE TABLE unidmedida (
  unidmed_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unidmed_nome  TEXT NOT NULL

);

-- =========================
-- Tabela "tipopagamento"
-- =========================
CREATE TABLE tipopagamento (
  tipopag_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipopag_nome  TEXT NOT NULL
);

-- =========================
-- Tabela "produto"
-- =========================
CREATE TABLE produto (
  produto_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_nome         TEXT NOT NULL,
  produto_descricao    TEXT,
  produto_valorpago    NUMERIC(12,2),
  produto_valorvenda   NUMERIC(12,2),

  unidmed_id           BIGINT REFERENCES unidmedida(unidmed_id),
  categoria_id         BIGINT REFERENCES categoria(categoria_id),

  usuario_id           UUID NOT NULL REFERENCES usuario(usuario_id) ON DELETE RESTRICT
);

-- =========================
-- Tabela "compra"
-- =========================
CREATE TABLE compra (
  compra_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_data     DATE NOT NULL,
  compra_nrfiscal TEXT,
  compra_total    NUMERIC(14,2),
  compra_nparcelas INTEGER,
  compra_status   TEXT,

  fornecedor_id   UUID REFERENCES fornecedor(fornecedor_id),
  tipopag_id      BIGINT REFERENCES tipopagamento(tipopag_id),

  usuario_id      UUID NOT NULL REFERENCES usuario(usuario_id) ON DELETE RESTRICT
);

-- =========================
-- Tabela "venda"
-- =========================
CREATE TABLE venda (
  venda_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venda_data    DATE NOT NULL,
  venda_total   NUMERIC(14,2),

  tipopag_id    BIGINT REFERENCES tipopagamento(tipopag_id),

  usuario_id    UUID NOT NULL REFERENCES usuario(usuario_id) ON DELETE RESTRICT
);

-- =========================
-- Tabela "itenscompra"
-- (herda tenant via compra)
-- =========================
CREATE TABLE itenscompra (
  itc_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id   BIGINT NOT NULL REFERENCES compra(compra_id) ON DELETE CASCADE,
  produto_id  BIGINT NOT NULL REFERENCES produto(produto_id),
  itc_qtde    NUMERIC(12,3),
  itc_valor   NUMERIC(12,2)
);

-- =========================
-- Tabela "itensvenda"
-- (herda tenant via venda)
-- =========================
CREATE TABLE itensvenda (
  itv_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venda_id    BIGINT NOT NULL REFERENCES venda(venda_id) ON DELETE CASCADE,
  produto_id  BIGINT NOT NULL REFERENCES produto(produto_id),
  itv_qtde    NUMERIC(12,3),
  itv_valor   NUMERIC(12,2),
  itv_custo   NUMERIC(12,2)
);

-- Índices por FK
CREATE INDEX idx_produto_unidmed     ON produto(unidmed_id);
CREATE INDEX idx_produto_categoria   ON produto(categoria_id);
CREATE INDEX idx_compra_fornecedor   ON compra(fornecedor_id);
CREATE INDEX idx_compra_tipopag      ON compra(tipopag_id);
CREATE INDEX idx_venda_tipopag       ON venda(tipopag_id);
CREATE INDEX idx_itenscompra_compra  ON itenscompra(compra_id);
CREATE INDEX idx_itenscompra_produto ON itenscompra(produto_id);
CREATE INDEX idx_itensvenda_venda    ON itensvenda(venda_id);
CREATE INDEX idx_itensvenda_produto  ON itensvenda(produto_id);

-- Índices por tenant
CREATE INDEX idx_fornecedor_usuario  ON fornecedor(usuario_id);
CREATE INDEX idx_categoria_usuario   ON categoria(usuario_id);
CREATE INDEX idx_produto_usuario     ON produto(usuario_id);
CREATE INDEX idx_compra_usuario      ON compra(usuario_id);
CREATE INDEX idx_venda_usuario       ON venda(usuario_id);


-- Função helper para ler o tenant atual da sessão
CREATE OR REPLACE FUNCTION tenant_id()
RETURNS UUID
LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.current_usuario', true), '')::uuid
$$;

-- Ativa RLS em todas as tabelas de dados
ALTER TABLE fornecedor     ENABLE ROW LEVEL SECURITY;
ALTER TABLE categoria      ENABLE ROW LEVEL SECURITY;
ALTER TABLE unidmedida     ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipopagamento  ENABLE ROW LEVEL SECURITY;
ALTER TABLE produto        ENABLE ROW LEVEL SECURITY;
ALTER TABLE compra         ENABLE ROW LEVEL SECURITY;
ALTER TABLE venda          ENABLE ROW LEVEL SECURITY;
ALTER TABLE itenscompra    ENABLE ROW LEVEL SECURITY;
ALTER TABLE itensvenda     ENABLE ROW LEVEL SECURITY;

-- Políticas por tenant (tabelas com coluna usuario_id)
CREATE POLICY rls_fornecedor_by_tenant   ON fornecedor
  USING      (usuario_id = tenant_id())
  WITH CHECK (usuario_id = tenant_id());

CREATE POLICY rls_categoria_by_tenant    ON categoria
  USING      (usuario_id = tenant_id())
  WITH CHECK (usuario_id = tenant_id());

CREATE POLICY rls_produto_by_tenant      ON produto
  USING      (usuario_id = tenant_id())
  WITH CHECK (usuario_id = tenant_id());

CREATE POLICY rls_compra_by_tenant       ON compra
  USING      (usuario_id = tenant_id())
  WITH CHECK (usuario_id = tenant_id());

CREATE POLICY rls_venda_by_tenant        ON venda
  USING      (usuario_id = tenant_id())
  WITH CHECK (usuario_id = tenant_id());

-- Itens herdam tenant do "pai" (e também garantimos que o produto é do mesmo tenant)
CREATE POLICY rls_itenscompra_by_tenant ON itenscompra
  USING (
    EXISTS (
      SELECT 1 FROM compra c
       WHERE c.compra_id = itenscompra.compra_id
         AND c.usuario_id = tenant_id()
    )
    AND EXISTS (
      SELECT 1 FROM produto p
       WHERE p.produto_id = itenscompra.produto_id
         AND p.usuario_id = tenant_id()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM compra c
       WHERE c.compra_id = itenscompra.compra_id
         AND c.usuario_id = tenant_id()
    )
    AND EXISTS (
      SELECT 1 FROM produto p
       WHERE p.produto_id = itenscompra.produto_id
         AND p.usuario_id = tenant_id()
    )
  );

CREATE POLICY rls_itensvenda_by_tenant ON itensvenda
  USING (
    EXISTS (
      SELECT 1 FROM venda v
       WHERE v.venda_id = itensvenda.venda_id
         AND v.usuario_id = tenant_id()
    )
    AND EXISTS (
      SELECT 1 FROM produto p
       WHERE p.produto_id = itensvenda.produto_id
         AND p.usuario_id = tenant_id()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM venda v
       WHERE v.venda_id = itensvenda.venda_id
         AND v.usuario_id = tenant_id()
    )
    AND EXISTS (
      SELECT 1 FROM produto p
       WHERE p.produto_id = itensvenda.produto_id
         AND p.usuario_id = tenant_id()
    )
  );

-- Opcional: força RLS (sem policy = sem acesso)
ALTER TABLE fornecedor     FORCE ROW LEVEL SECURITY;
ALTER TABLE categoria      FORCE ROW LEVEL SECURITY;
ALTER TABLE unidmedida     FORCE ROW LEVEL SECURITY;
ALTER TABLE tipopagamento  FORCE ROW LEVEL SECURITY;
ALTER TABLE produto        FORCE ROW LEVEL SECURITY;
ALTER TABLE compra         FORCE ROW LEVEL SECURITY;
ALTER TABLE venda          FORCE ROW LEVEL SECURITY;
ALTER TABLE itenscompra     FORCE ROW LEVEL SECURITY;
ALTER TABLE itensvenda      FORCE ROW LEVEL SECURITY;


